global:
  enabled: false
  #  dnsPolicy: "ClusterFirst"   # Change the dnsPolicy value from "ClusterFirst" to
  image: "hashicorp/consul:1.15.2"
  datacenter: dc-hadar-kandula
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
externalServers:
  enabled: true
  hosts: [consul.service.consul]
  httpPort: 8500
server:
  replicas: 0 # Set the number of server replicas to 0 to disable the server component
client:
  enabled: true
  exposeGossipPorts: true
  join:
    - "provider=aws tag_key=consul tag_value=true"
  #grpc: true
  nodeMeta:
    pod-name: ${HOSTNAME}
    host-ip: ${HOST_IP}
dns:
  enabled: true
#    upstreams:
#      - "consul-consul-dns.consul.svc"
connectInject:
  enabled: false

syncCatalog:
  enabled: true
  image: hashicorp/consul-k8s-control-plane:0.49.5
#  k8sAllowNamespaces: ["*"]