apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  namespace: kandula

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      containers:
      - name: kandula
        image: hadarneu/kandula:1.2
        # volumeMounts:
        #   - name: secrets-kandula
        #     mountPath: /etc/secret
        #     readOnly: true
        # envFrom:
        # - configMapRef:
        #     name: config-map-kandula

        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: AWS_DEFAULT_REGION
        - name: FLASK_APP
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: FLASK_APP
        - name: FLASK_DEBUG
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: FLASK_DEBUG
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: SECRET_KEY
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secrets-kandula
              key: DB_HOST
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      # volumes:
      # - name: secrets-kandula
      #   secret:
      #     secretName: secrets-kandula