apiVersion: batch/v1
kind: Job
metadata:
  name: dns
spec:
  template:
    spec:
      containers:
        - name: dns
          image: anubhavmishra/tiny-tools
          command: ["dig", "consul.service.consul:8500"]
      restartPolicy: Never
  backoffLimit: 4