apiVersion: v1
kind: Service
metadata:
  name: kandula-app-lb-service
  namespace: kandula
spec:
  selector:
    app: kandula-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30037
      protocol: TCP
