---
plugin: aws_ec2

regions:
  - us-west-2
filters:
  instance-state-name : running

keyed_groups:
  - prefix: tag
    key: tags
  - key: tags.service
    separator: ''

exclude_filters:
  - tag:service:
    - 'ansible'

hostnames: network-interface.addresses.private-ip-address

