---
- name: Configure elastic
  hosts: tag_service_elastic
  become: true
  tasks:

    - name: Configure elastic service
      copy:
        dest: "/etc/elasticsearch/elasticsearch.yml"
        content: |
          # Path to directory where to store the data (separate multiple locations by comma):
          #
          path.data: /var/lib/elasticsearch
          #
          # Path to log files:
          #
          path.logs: /var/log/elasticsearch
          # ---------------------------------- Network -----------------------------------
          #
          # By default Elasticsearch is only accessible on localhost. Set a different
          # address here to expose this node on the network:
          #
          # network.host: kibana.service.consul DIDNT WORK - error- failed to bind
          network.host: 0.0.0.0
          # By default Elasticsearch listens for HTTP traffic on the first free port it
          # finds starting at 9200. Set a specific HTTP port here:
          #
          http.port: 9200
          #
          #
          #
          discovery.seed_hosts: ["127.0.0.1", "[::1]"]
          cluster.initial_master_nodes: ["node-1"]
          # For more information, consult the network module documentation.

    - name: register consul service
      command: consul services register -name elastic -port 9200
    
    - name: Enable elastic service on boot
      systemd:
        name: "elasticsearch"
        enabled: yes

    - name: Start elastic service
      service:
        name: "elasticsearch"
        state: "started"
        enabled: true
