---
- name: Configure Grafana
  hosts: tag_service_grafana
  gather_facts: no
  become: yes

  tasks:
    - name: Copy datasource configuration
      copy:
        src: /home/ubuntu/Kandula/ansible-playbooks/datasources.yaml
        dest: /etc/grafana/provisioning/datasources/datasource.yaml

    - name: Copy dashboard configuration
      copy:
        src: /home/ubuntu/Kandula/ansible-playbooks/dashboards.yaml
        dest: /etc/grafana/provisioning/dashboards/dashboard.yaml

    - name: Restart Grafana service
      service:
        name: grafana-server
        state: restarted
